# Generated by Django 5.2.3 on 2025-07-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaimodel',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
