# Generated by Django 5.2.4 on 2025-07-10 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rProject', '0002_chaimodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaimodel',
            name='type',
            field=models.CharField(choices=[('ma', 'mango chai'), ('um', 'umesh chai'), ('cm', 'chai master')], default='ML', max_length=2),
        ),
        migrations.CreateModel(
            name='chaiCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('issuseFeild', models.DateTimeField(default=django.utils.timezone.now)),
                ('vaild_until', models.DateTimeField()),
                ('chai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='rProject.chaimodel')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('chai_varities', models.ManyToManyField(related_name='stores', to='rProject.chaimodel')),
            ],
        ),
    ]
